[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "exprfn"
author = "Paul Moore"
author-email = "p.f.moore@gmail.com"
home-page = "https://github.com/pfmoore/exprfn"
classifiers = ["License :: OSI Approved :: MIT License"]

